// "use client";
import "./globals.css";

export const metadata = {
  title: "LSP - App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <div className="flex h-screen">
//         <Sidebar />
//         <div className="flex-1 ml-64 p-6">
//           <Header />
//           <body>{children}</body>
//         </div>
//       </div>
//     </html>
//   );
// }
